name: bharatx_flutter_sample
description: Sample Project for BharatX Integration

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bharatx_flutter_startup: 1.0.3-release2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

flutter:
  uses-material-design: true
